### PR TITLE
Family ID proposal

### PR DESCRIPTION
**Pull request by mmoskal**

### CODE REVIEW

**Comment by ladyada** [comment]
yah - i think its probably a good idea! we'd have to update the bootloaders but at least this way we'd just have the UF2 reject rather than reboot and hang instantly

**Comment by mmoskal** [comment]
Current bootloader would accept files with family Id, so we can update MakeCode to embed the Id. And we would change the bootloader to accept files with the right family id or none at all so we are backwards compatible with existing uf2 files. 

I guess we could make the bootloader blink angrily when it gets wrong id.

**Comment by ladyada** [comment]
S.O.S. :)

**Comment by hathach** [comment]
my two cents, I think we should have an uint32_t for family id, and uin32_t for firmware_version (optional) in case people decide to modify bootloader to prohibit a downgrade, or use that to upgrade to only to compatible firmware (same MSB byte or something).

both family id and firmware_version are best to place right before the magicEnd !?!

**Comment by mmoskal** [comment]
On very small devices you don't have enough memory to buffer entire block (eg interface chip on Uno has 0.5k of which you're already using some), so I would rather have the family Id in front.

For versions then I guess we can add a flag saying it's present and place it at the end

**Comment by hathach** [comment]
ah right, it could be trouble if the chip couldn't hold the whole 512 bytes. In that case, the family ID may be placed at offset 28, the specs say filesize or reserved. We could have an flag bit to to indicate that these 4 bytes has family meaning, otherwise back to the filesize/reserve.

**Comment by mmoskal** [comment]
right, this is exactly what it says in the PR ;)

**Comment by hathach** [comment]
@mmoskal superb, sorry to miss that. Though, after taking a look at the PR modification, I think you should only use 2 bytes for the MCU family. Since 2 bytes is enough for all the mcu family in the world. 

Extra 2 bytes could be used for other purpose, such as vendor product ID ( --productid ) e.g we wouldn't want an incompatible firmware build from other vendors ( also using nrf52) to flash on our product. This could corrupt thing like filesystem that we used to store bonds data/setting etc ...  Hacker can easily overwrite this by generating uf2 with the same productid (no way to prevent who that have the will to hack :D )

**Comment by mmoskal** [comment]
I think if people create incompatible version of the firmware, they can just come up with an alternative familyID for whatever they are doing. Using 32 bits the probability of collision is very low.

**Comment by hathach** [comment]
Agreed, that is perfect.

**Pull request merged**
