### PR TITLE
add IDs for ESP32-C6 and ESP32-P4

### PR DESCRIPTION
**Pull request by Icarus113**
The IDs were generated by the random number generator at https://microsoft.github.io/uf2/patcher.

### CODE REVIEW

**Comment by dobairoland** [comment]
For reference, these are new chips of Espressif.

- https://www.espressif.com/en/news/ESP32-P4
- https://www.espressif.com/en/news/ESP32_C6

**Comment by mmoskal** [comment]
thank you!

**Comment by dobairoland** [comment]
Thank you for the merge @mmoskal!

**Comment by Icarus113** [comment]
thank you~ @mmoskal

**Pull request merged**
