### PR TITLE
Add family IDs for missing chips of Espressif

### PR DESCRIPTION
**Pull request by dobairoland**
The IDs were generated randomly with https://microsoft.github.io/uf2/patcher/.

### CODE REVIEW

**Comment by mmoskal** [comment]
Thanks! If you have some tooling for ESP32+UF2, let me know!

**Comment by ladyada** [comment]
we ported UF2 to ESP32-S2 (and iMX RT) here
https://github.com/adafruit/tinyuf2

**Comment by dobairoland** [comment]
Thank you @mmoskal for the merge. Yes, I will. My plan is to add it into [esp-idf](https://github.com/espressif/esp-idf). I'm not sure when that will happen.

@ladyada Thank you for pointing this out. I'll look at your repo. However, I need UF2 not just for the bootloader and I need it for all ESP chips.

**Comment by mmoskal** [comment]
@dobairoland do you already have some devices with ESP32-S2 ID in the wild? there's an existing bootloader using a different one, with shipped devices

**Comment by dobairoland** [comment]
@mmoskal No, I haven't used these IDs in any final products yet. If you want to change them to something else then there is still time and possibility for me to do it.

**Comment by mmoskal** [comment]
@dobairoland it has now been updated, thanks!

**Pull request merged**
